title:            Vox Today
description:      We make the news

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# When testing locally leave blank or use http://localhost:4000
## using http://localhost:4000 doesn't seem to affect local testing
#url: http://localhost:4000
url: http://Vox.Today

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Happening Now!'
    url: '/CurrentEvents/'
  - title: 'Topics'
    url: '#'
    submenu:
      - title: 'Politics'
        url: '/intro/code-highlighting-post/'
      - title: 'Business'
        url: '/intro/sample-post/'
      - title: 'Technology'
        url: '/intro/code-highlighting-post/'
      - title: 'Environment'
        url: '/intro/sample-post/'
      - title: 'Around The World'
        url: '/intro/sample-post/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
## TODO: Change to "top categories" | until then use categories with restraint
# show only top n-categories so list doesn't grow past n = 4 - 8
# See line 21 of /_includes/header.html
    type: 'categories'
  - title: '@Vox Today'
    url: '/about/'

# Owner/author information
owner:
  name:           Vox Today
  site:           http://Vox.Today
  avatar:         images/avatar.jpg
  bio:            "We create and curate the news you want"
  email:          contact@Vox.Today
  # Twitter nick for use in Twitter cards and follow button.
  twitter: Vox_Today # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: VoxToday

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/VoxToday"
  - title: "Facebook"
    url: "https://www.facebook.com/VoxToday"
  - title: "twitter"
    url: "https://twitter.com/Vox_Today"
## TODO Get a YouTube Account created, active and setup here
  # - title: "youtube"
  #   url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-90507913-1
google_verify: googlea56b03a05484af10
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# customizing kramdown markdown settings to GitHub flavor
kramdown:
    input:  GFM
    gfm_quirks: [paragraph_end]

## TODO: test hypothesis
# Not exactly sure about this line
# I believe it set's permalink settings to start with the setting
# so permalink: /coolpage/
# would be: /categories[category of post]/title[of post]/coolpage
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
